steps:
  - name: gcr.io/cloud-builders/git
    args:
      [
        'clone',
        'https://github.com/kevinsimper/kevinsimper.dk-images.git',
        'app/blog/posts/images',
      ]
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/kevinsimper/kevinsimper.dk:$SHORT_SHA', '.']
  - name: gcr.io/cloud-builders/docker
    args: ['push', 'gcr.io/kevinsimper/kevinsimper.dk:$SHORT_SHA']
