steps:
  - name: gcr.io/cloud-builders/git
    args:
      [
        'clone',
        'https://github.com/kevinsimper/kevinsimper.dk-images.git',
        'public/posts/images',
      ]
  - name: gcr.io/cloud-builders/docker
    id: 'build image'
    args: ['build', '-t', 'gcr.io/kevinsimper/kevinsimper.dk:$SHORT_SHA', '.']
  - name: gcr.io/cloud-builders/docker
    args: ['push', 'gcr.io/kevinsimper/kevinsimper.dk:$SHORT_SHA']
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "$BRANCH_NAME" == "master" ]]; then
          gcloud beta run deploy kevinsimper --image=gcr.io/kevinsimper/kevinsimper.dk:$SHORT_SHA --region=europe-west1 --platform=managed
        else
          echo "Skipping . . ."
        fi
