// Generated by Xata Codegen 0.26.6. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "mountains",
    columns: [
      { name: "name", type: "string" },
      { name: "country", type: "string" },
      { name: "startLat", type: "float" },
      { name: "startLon", type: "float" },
      { name: "endLat", type: "float" },
      { name: "endLon", type: "float" },
      { name: "length", type: "int" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Mountains = InferredTypes["mountains"];
export type MountainsRecord = Mountains & XataRecord;

export type DatabaseSchema = {
  mountains: MountainsRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://Kevin-Simper-s-workspace-gf8rf3.eu-west-1.xata.sh/db/cykelbjerge",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
