name: Build
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: run
      uses: ngalaiko/bazel-action@0.29.0
      with:
        args: build :build
